version: '2'
services:
  mongodb:
    image: mongo:3.2.5
    ports:
      - '27017:27017'
  eureka-icase:
    image: eureka-icase:latest
    ports:
      - '9671:9671'
  spring-icase:
    image: spring-icase:latest
    ports:
      - '8080:8080'
    depends_on:
      - mongodb
  api-gateway-icase:
    image: api-gateway-icase:latest
    ports:
      - '8075:8075'
    depends_on:
      - spring-icase
  front-react:
    image: react-icase:latest
    ports:
      - '4200:4200'
